In [33]:
#ventas mensuales
import numpy as np
ventas_mensuales= np.array([[21,25,35,10],[11,15,12,4],[47,54,51,50],[21,22,22,22],[19,20,18,19],[6,10,9,8],[28,22,33,22],[11,15,14,16],[9,2,3,2],[10,9,9,8],[32,29,31,33],[12,16,24,17]])
ventas_mensuales.shape
(5, 12)
print(ventas_mensuales)



StatementMeta(SPK09, 3, 34, Finished, Available)

[[21 25 35 10]
 [11 15 12  4]
 [47 54 51 50]
 [21 22 22 22]
 [19 20 18 19]
 [ 6 10  9  8]
 [28 22 33 22]
 [11 15 14 16]
 [ 9  2  3  2]
 [10  9  9  8]
 [32 29 31 33]
 [12 16 24 17]]


In [34]:
t=sum(ventas_mensuales)
print("el total de ventas fue") 
print(t)

StatementMeta(SPK09, 3, 35, Finished, Available)

el total de ventas fue
[227 239 261 211]
